### ISSUE TITLE
App requires bundler v 0.8

### ISSUE THREAD

**Issue by treffiletti** [trevorturk/eldorado#1]
Just a friendly notice that the app runs out of the box with the current readme off bundler 0.8 so a 
sudo gem install bundler -v 0.8 will work in place of the gem install bundler that's currently instructed.  Hopefully this will save someone else the hour and a half that I spent trying to configure it for bundler 0.9.  Might be nice to see an upgrade to 0.9 at some point though.  Great app.

**Comment by trevorturk** [comment]
Any tips on how to get bundler 0.9 working? I'm having no luck.

**Comment by trevorturk** [comment]
giving up on bundler - pull from master to go back to config.gem and .gems for heroku
