### ISSUE TITLE
German translation broken.

### ISSUE THREAD

**Issue by ghost** [trevorturk/eldorado#4]
Just installed El Dorado and started playing around with it - when trying to create an new event, I get 'Date translation missing: de, activerecord, errors, models, event, attributes, date, blank' - so I went to the Heroku demo page and tried to post into the forum, which resulted in the error 'Forum translation missing: de, activerecord, errors, models, topic, attributes, forum_id, blank' - I guess the translations are either missing or incomplete. Could someone please tell me how to fix this? I have no real experience with Ruby and i18n, so I don't know where to look for the translation files. Thanks!

EDIT: It seems this only happens when I don't select a date while trying to create an event - selecting a date makes the error go away.

**Comment by trevorturk** [comment]
I'm not sure, but I think I fixed a similar error with the english here:

http://github.com/trevorturk/eldorado/commit/f53bdddcc4e84ca9c525cfb94c84f6a1cf56839a

Perhaps you could do the same with the de version? I'd happily accept a pull request if you figure it out. Thanks!

**Comment by trevorturk** [comment]
I think this has been fixed.
