### ISSUE TITLE
CGI::Session::CookieStore::TamperedWithCookie

### ISSUE THREAD

**Issue by nekote** [trevorturk/eldorado#7]
Hi Trevor,

Thing have been going excellently since the PusherApp implementation that you strongly advised was accomplished.

Only oddity is a LoggedException of:
CGI::Session::CookieStore::TamperedWithCookie

6 or 8 times, per day
Since Sept 1, 2011:
controller_name     count(`controller_name`)
topics  203
articles    87
uploads 14
avatars     6
posts   5
users   3

Before delving into the IP source info, I'm hoping you would be kind enough to provide some insight as to what I should likely be looking for.

Thanks.

**Comment by trevorturk** [comment]
Sorry, but I'm not sure about that one. I'd suggest looking for where the exception is coming from. I think it's to do with sessions stored in the cookie, but I'm not sure. You could look for alternatives to that?
