### ISSUE TITLE
BBcode list problem

### ISSUE THREAD

**Issue by miphe** [trevorturk/eldorado#8]
There seems to be a problem when writing some BBcode (this example, in a forum topic).

When writing the following:

``` text
[list]
[*] item 1
[*] item 2
[/list]
```

.. I should get:

``` html
<ul>
<li>item 1</li>
<li>item 2</li>
</ul>
```

.. but instead I get:

``` html
<ul>
[*] item 1<br>
[*] item 2<br>
</ul>
```

**Comment by trevorturk** [comment]
I suppose this would be a problem with the bbcode plugin being used. I'd suggest swapping that out for something else more advanced...? Sorry, but I'm not doing much work on El Dorado anymore, so I'm going to close this out for now. Good luck in trying to find a fix!
