### ISSUE TITLE
Eldorado Issue

### ISSUE THREAD

**Issue by Dwellingdragon** [trevorturk/eldorado#9]
I'm trying ot make it so that if I go to http://dexndes.com/eldorado it comes up with the eldorado software. But currently it doesn't, it only comes up when I enter the IP:3000.  Is there a way to change that?

**Comment by trevorturk** [comment]
Sorry but I'm not really supporting this app anymore. Good luck!

On Apr 26, 2012, at 6:24 PM, Dwellingdragon
reply@reply.github.com
wrote:

**Comment by Dwellingdragon** [comment]
Well that is one hell of a debbie downer lol.  Do you have/know other apps similar to eldorado? I really love that idea and would love to have something like that that's supported.

**Comment by trevorturk** [comment]
Not really, no. Sorry!

On Apr 26, 2012, at 7:19 PM, Dwellingdragon
reply@reply.github.com
wrote:

**Comment by Dwellingdragon** [comment]
Lol well shit. Thanks xD.

**Comment by trevorturk** [comment]
If I were you, I'd use some WordPress / BBPress combo honestly.

On Apr 26, 2012, at 8:14 PM, Dwellingdragon
reply@reply.github.com
wrote:
